import React, { useState } from 'react';
import {
  Bell,
  AlertTriangle,
  AlertCircle,
  CheckCircle2,
  Trash2,
  ShoppingBag,
  Copy,
  Check,
  RotateCcw,
  Sparkles,
} from 'lucide-react';
import { AlertNotification, ContainerNode } from '../types';

interface AlertsViewProps {
  alerts: AlertNotification[];
  containers: ContainerNode[];
  onClearAlerts: () => Promise<void>;
  onMarkRead: (id: string) => Promise<void>;
}

export const AlertsView: React.FC<AlertsViewProps> = ({
  alerts,
  containers,
  onClearAlerts,
  onMarkRead,
}) => {
  const [copiedGroceryList, setCopiedGroceryList] = useState(false);
  const [filter, setFilter] = useState<'all' | 'unread'>('all');

  // Compute smart grocery list from all containers that are low or critical
  const lowItems = containers.filter((c) => c.status === 'low' || c.status === 'critical');

  const filteredAlerts = filter === 'unread' ? alerts.filter((a) => !a.read) : alerts;

  const copyShoppingList = () => {
    if (lowItems.length === 0) return;
    const text = lowItems
      .map((item) => {
        const neededGrams = Math.max(100, item.capacity_g - item.raw_weight_g);
        return `- [ ] ${item.ingredient}: approx ${neededGrams}g (Current: ${item.fill_pct}% remaining)`;
      })
      .join('\n');

    navigator.clipboard.writeText(`Kitchen Restock List:\n${text}`);
    setCopiedGroceryList(true);
    setTimeout(() => setCopiedGroceryList(false), 2000);
  };

  const formatTimestamp = (timestamp: number) => {
    const diff = Math.floor((Date.now() - timestamp) / 1000);
    if (diff < 60) return 'Just now';
    if (diff < 3600) return `${Math.floor(diff / 60)} minutes ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)} hours ago`;
    return new Date(timestamp).toLocaleDateString();
  };

  return (
    <div className="space-y-6">
      {/* Top Banner: Smart Shopping List Generated by Sensor Jars */}
      <div className="bg-white rounded-2xl p-5 sm:p-6 border border-stone-200 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-amber-100 text-amber-900">
              <ShoppingBag className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-bold text-stone-900">
                Automated Restock & Grocery List
              </h2>
              <p className="text-xs text-stone-500">
                Generated automatically when smart jar load cells drop below threshold.
              </p>
            </div>
          </div>

          {lowItems.length > 0 && (
            <button
              onClick={copyShoppingList}
              className="flex items-center space-x-1.5 px-3 py-1.5 rounded-xl bg-stone-900 hover:bg-stone-800 text-white text-xs font-semibold shadow-xs transition-colors self-start sm:self-auto"
            >
              {copiedGroceryList ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  <span>List Copied</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy Shopping List</span>
                </>
              )}
            </button>
          )}
        </div>

        {lowItems.length > 0 ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {lowItems.map((item) => {
              const neededGrams = Math.max(50, item.capacity_g - item.raw_weight_g);
              return (
                <div
                  key={item.id}
                  className={`p-3 rounded-xl border flex items-center justify-between ${
                    item.status === 'critical'
                      ? 'bg-rose-50/70 border-rose-200 text-rose-900'
                      : 'bg-amber-50/70 border-amber-200 text-amber-900'
                  }`}
                >
                  <div>
                    <span className="text-[10px] font-mono uppercase tracking-wider block text-stone-500">
                      {item.id} &bull; {item.category}
                    </span>
                    <span className="font-bold text-sm block">{item.ingredient}</span>
                    <span className="text-xs opacity-80">Need to buy ~{neededGrams}g</span>
                  </div>
                  <span
                    className={`px-2 py-0.5 rounded text-xs font-bold ${
                      item.status === 'critical'
                        ? 'bg-rose-200 text-rose-900'
                        : 'bg-amber-200 text-amber-900'
                    }`}
                  >
                    {item.fill_pct}% left
                  </span>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="p-4 rounded-xl bg-emerald-50/60 border border-emerald-100 flex items-center space-x-3 text-emerald-800 text-xs">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>All pantry containers are well-stocked! No grocery action required.</span>
          </div>
        )}
      </div>

      {/* Sensor Push Messages & Alert Feed */}
      <div className="bg-white rounded-2xl p-5 sm:p-6 border border-stone-200 shadow-xs space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-stone-100 pb-3">
          <div className="flex items-center space-x-2">
            <Bell className="w-5 h-5 text-stone-700" />
            <h3 className="font-bold text-stone-900 text-base">Sensor Push Notifications</h3>
            <span className="text-xs px-2 py-0.5 rounded-full bg-stone-100 text-stone-600 font-mono">
              {alerts.length} total
            </span>
          </div>

          <div className="flex items-center space-x-2">
            <div className="flex items-center space-x-1 bg-stone-100 p-1 rounded-xl text-xs">
              <button
                onClick={() => setFilter('all')}
                className={`px-2.5 py-1 rounded-lg font-medium transition-colors ${
                  filter === 'all' ? 'bg-white text-stone-900 shadow-2xs' : 'text-stone-600'
                }`}
              >
                All
              </button>
              <button
                onClick={() => setFilter('unread')}
                className={`px-2.5 py-1 rounded-lg font-medium transition-colors ${
                  filter === 'unread' ? 'bg-white text-stone-900 shadow-2xs' : 'text-stone-600'
                }`}
              >
                Unread ({alerts.filter((a) => !a.read).length})
              </button>
            </div>

            {alerts.length > 0 && (
              <button
                onClick={onClearAlerts}
                className="p-1.5 text-stone-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-colors"
                title="Clear all alerts"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>

        {filteredAlerts.length > 0 ? (
          <div className="space-y-2.5">
            {filteredAlerts.map((alert) => (
              <div
                key={alert.id}
                onClick={() => !alert.read && onMarkRead(alert.id)}
                className={`p-3.5 rounded-xl border transition-all flex items-start justify-between gap-3 cursor-pointer ${
                  !alert.read
                    ? 'bg-amber-50/40 border-amber-200'
                    : 'bg-stone-50/50 border-stone-200/80 hover:bg-stone-50'
                }`}
              >
                <div className="flex items-start space-x-3">
                  <div className="mt-0.5 shrink-0">
                    {alert.type === 'critical_stock' ? (
                      <AlertCircle className="w-4 h-4 text-rose-600" />
                    ) : alert.type === 'low_stock' ? (
                      <AlertTriangle className="w-4 h-4 text-amber-600" />
                    ) : (
                      <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    )}
                  </div>
                  <div>
                    <div className="flex items-center space-x-2 mb-0.5">
                      <span className="font-bold text-xs text-stone-900">{alert.ingredient}</span>
                      <span className="text-[10px] font-mono text-stone-400">({alert.container_id})</span>
                      {!alert.read && (
                        <span className="w-1.5 h-1.5 rounded-full bg-amber-500" />
                      )}
                    </div>
                    <p className="text-xs text-stone-700 leading-relaxed">{alert.message}</p>
                    <span className="text-[10px] text-stone-400 mt-1 block">
                      {formatTimestamp(alert.timestamp)}
                    </span>
                  </div>
                </div>

                {!alert.read && (
                  <span className="text-[10px] font-medium text-amber-700 whitespace-nowrap bg-amber-100 px-2 py-0.5 rounded-full">
                    Mark Read
                  </span>
                )}
              </div>
            ))}
          </div>
        ) : (
          <div className="p-8 text-center text-stone-400 text-xs font-sans">
            <Bell className="w-8 h-8 mx-auto mb-2 text-stone-300" />
            <p>No notifications in this view.</p>
          </div>
        )}
      </div>
    </div>
  );
};
